
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  # database: Blog_development

test:
  <<: *default
  # database: Blog_test

production:
  <<: *default
  # database: Blog_production
  # username: Blog
  # password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
